const authClient = useAuth()
export const {
  acceptInvitation: useOrgAcceptInvitation,
  cancelInvitation: useOrgCancelInvitation,
  checkRolePermission: useOrgCheckRolePermission,
  checkSlug: useOrgCheckSlug,
  create: useOrgCreate,
  delete: useOrgDelete,
  getActiveMember: useOrgGetActiveMember,
  getFullOrganization: useOrgGetFullOrganization,
  getInvitation: useOrgGetInvitation,
  hasPermission: useOrgHasPermission,
  inviteMember: useOrgInviteMember,
  leave: useOrgLeave,
  list: useOrgList,
  listInvitations: useOrgListInvitations,
  rejectInvitation: useOrgRejectInvitation,
  removeMember: useOrgRemoveMember,
  setActive: useOrgSetActive,
  update: useOrgUpdate,
  updateMemberRole: useOrgUpdateMemberRole,
} = authClient.client.organization
