const authClient = useAuth()
export const {
  changeEmail: useUserChangeEmail,
  changePassword: useUserChangePassword,
  deleteUser: useUserDelete,
  forgetPassword: useUserForgetPassword,
  getSession: useUserGetSession,
  linkSocial: useUserLinkSocial,
  listAccounts: useUserListAccounts,
  listSessions: useUserListSessions,
  refreshToken: useUserRefreshToken,
  resetPassword: useUserResetPassword,
  revokeOtherSessions: useUserRevokeOtherSessions,
  revokeSession: useUserRevokeSession,
  revokeSessions: useUserRevokeSessions,
  sendVerificationEmail: useUserSendVerificationEmail,
  signIn: useUserSignIn,
  signOut: useUserSignOut,
  signUp: useUserSignUp,
  unlinkAccount: useUserUnlinkAccount,
  updateUser: useUserUpdate,
  useActiveMember: useUserActiveMember,
  useActiveOrganization: useUserActiveOrganization,
  useListOrganizations: useUserListOrganizations,
  useSession: useUserSession,
  verifyEmail: useUserVerifyEmail,
} = authClient.client
