enableTelemetry: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.8.1.cjs

injectEnvironmentFiles:
- .env?

npmAuthToken: "${YARN_NPM_AUTH_TOKEN:-}"

npmScopes:
  sozdev:
    npmPublishRegistry: "https://gitea.local/api/packages/sozdev/npm/"
    npmRegistryServer: "https://gitea.local/api/packages/sozdev/npm/"