/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { CommentMemberRole } from './commentMemberRole';
import type { CommentMemberUser } from './commentMemberUser';

export type CommentMember = {
  id?: string;
  role?: CommentMemberRole;
  user?: CommentMemberUser;
};
