/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { CommentMember } from './commentMember';

export interface Comment {
  id: string;
  reviewFlowId: string;
  memberId: string;
  content: string;
  /** @nullable */
  fieldReference?: string | null;
  createdAt: string;
  member?: CommentMember;
}
