/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorData } from './errorData';

export interface Error {
  statusCode?: number;
  message?: string;
  data?: ErrorData;
}
