/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { FileAccessLevel } from './fileAccessLevel';
import type { FileUploader } from './fileUploader';
import type { FileFolderProperty } from './fileFolderProperty';

export interface File {
  id: string;
  filename: string;
  originalName: string;
  mimeType: string;
  size: number;
  accessLevel: FileAccessLevel;
  /** @nullable */
  description?: string | null;
  organizationId: string;
  uploaderMemberId: string;
  /** @nullable */
  folderId?: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  accessedAt?: string | null;
  deleted?: boolean;
  /** @nullable */
  lastModifiedBy?: string | null;
  version: number;
  uploader?: FileUploader;
  /** @nullable */
  folder?: FileFolderProperty;
}
