/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { FileFolderCreator } from './fileFolderCreator';

export interface FileFolder {
  id: string;
  name: string;
  /** @nullable */
  description?: string | null;
  organizationId: string;
  creatorMemberId: string;
  /** @nullable */
  parentId?: string | null;
  /** @nullable */
  path?: string | null;
  level: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  lastModifiedBy?: string | null;
  version: number;
  creator?: FileFolderCreator;
  /** @nullable */
  parent?: FileFolder;
  /** @nullable */
  filesCount?: number | null;
  /** @nullable */
  childrenCount?: number | null;
}
