/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { File } from './file';
import type { FileShareMember } from './fileShareMember';

export interface FileShare {
  id: string;
  fileId: string;
  memberId: string;
  createdAt: string;
  /** @nullable */
  expiresAt?: string | null;
  file?: File;
  member?: FileShareMember;
}
