/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */

export type FileAccessLevel = typeof FileAccessLevel[keyof typeof FileAccessLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileAccessLevel = {
  PRIVATE: 'PRIVATE',
  ORGANIZATION: 'ORGANIZATION',
  PUBLIC: 'PUBLIC',
} as const;
