/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */

export type FileUploaderRole = typeof FileUploaderRole[keyof typeof FileUploaderRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileUploaderRole = {
  owner: 'owner',
  admin: 'admin',
  reviewer: 'reviewer',
  executor: 'executor',
  member: 'member',
} as const;
