/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { FormStatus } from './formStatus';
import type { FormCreator } from './formCreator';
import type { FormExecutor } from './formExecutor';
import type { FormOrganization } from './formOrganization';
import type { FormTemplateProperty } from './formTemplateProperty';
import type { FormField } from './formField';
import type { FormHistoryPropertyItem } from './formHistoryPropertyItem';
import type { FormReviewFlow } from './formReviewFlow';

export interface Form {
  id: string;
  title: string;
  /** @nullable */
  description?: string | null;
  status: FormStatus;
  organizationId: string;
  creatorMemberId: string;
  /** @nullable */
  executorMemberId?: string | null;
  /** @nullable */
  templateId?: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  lastModifiedBy?: string | null;
  version: number;
  creator?: FormCreator;
  /** @nullable */
  executor?: FormExecutor;
  organization?: FormOrganization;
  /** @nullable */
  template?: FormTemplateProperty;
  fields?: FormField[];
  history?: FormHistoryPropertyItem[];
  /** @nullable */
  reviewFlow?: FormReviewFlow;
}
