/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { FormUpdateStatus } from './formUpdateStatus';

export interface FormUpdate {
  title?: string;
  /** @nullable */
  description?: string | null;
  status?: FormUpdateStatus;
  /** @nullable */
  executorMemberId?: string | null;
}
