/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */

export type FormHistoryMemberRole = typeof FormHistoryMemberRole[keyof typeof FormHistoryMemberRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormHistoryMemberRole = {
  owner: 'owner',
  admin: 'admin',
  reviewer: 'reviewer',
  executor: 'executor',
  member: 'member',
} as const;
