/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { FormHistoryStatus } from './formHistoryStatus';
import type { FormHistoryData } from './formHistoryData';
import type { FormHistoryMember } from './formHistoryMember';

export interface FormHistory {
  id: string;
  formId: string;
  status: FormHistoryStatus;
  memberId: string;
  /** @nullable */
  data?: FormHistoryData;
  createdAt: string;
  member?: FormHistoryMember;
}
