/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { FormFieldType } from './formFieldType';
import type { FormFieldFilesItem } from './formFieldFilesItem';

export interface FormField {
  id: string;
  formId: string;
  name: string;
  type: FormFieldType;
  /** @nullable */
  value?: string | null;
  required?: boolean;
  /** @nullable */
  validationRules?: string | null;
  order: number;
  /** @nullable */
  options?: string | null;
  files?: FormFieldFilesItem[];
}
