/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { FormTemplateFieldUpdateType } from './formTemplateFieldUpdateType';

export interface FormTemplateFieldUpdate {
  name?: string;
  type?: FormTemplateFieldUpdateType;
  /** @nullable */
  defaultValue?: string | null;
  required?: boolean;
  /** @nullable */
  validationRules?: string | null;
  order?: number;
  /** @nullable */
  options?: string | null;
}
