/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */

export type FormHistoryStatus = typeof FormHistoryStatus[keyof typeof FormHistoryStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormHistoryStatus = {
  DRAFT: 'DRAFT',
  UNDER_REVIEW: 'UNDER_REVIEW',
  NEEDS_CHANGES: 'NEEDS_CHANGES',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;
