/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */

export interface FormCreate {
  title: string;
  /** @nullable */
  description?: string | null;
  organizationId: string;
  /** @nullable */
  templateId?: string | null;
  /** @nullable */
  executorMemberId?: string | null;
}
