/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { FormTemplateField } from './formTemplateField';

export interface FormTemplateFieldList {
  items: FormTemplateField[];
  total: number;
  limit: number;
  offset: number;
}
