/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */

export type FormTemplateFieldUpdateType = typeof FormTemplateFieldUpdateType[keyof typeof FormTemplateFieldUpdateType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormTemplateFieldUpdateType = {
  TEXT: 'TEXT',
  TEXTAREA: 'TEXTAREA',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  SELECT: 'SELECT',
  CHECKBOX: 'CHECKBOX',
  RADIO: 'RADIO',
  FILE: 'FILE',
} as const;
