/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */

export type ReviewFlowCreateStatus = typeof ReviewFlowCreateStatus[keyof typeof ReviewFlowCreateStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReviewFlowCreateStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
} as const;
