/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewFlowStatus } from './reviewFlowStatus';
import type { ReviewFlowForm } from './reviewFlowForm';
import type { ReviewFlowOrganization } from './reviewFlowOrganization';
import type { Comment } from './comment';

export interface ReviewFlow {
  id: string;
  formId: string;
  organizationId: string;
  status: ReviewFlowStatus;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  lastModifiedBy?: string | null;
  version: number;
  /** @nullable */
  form?: ReviewFlowForm;
  /** @nullable */
  organization?: ReviewFlowOrganization;
  /** @nullable */
  comments?: Comment[] | null;
}
