/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewFlow } from './reviewFlow';
import type { ReviewFlowListMeta } from './reviewFlowListMeta';

export interface ReviewFlowList {
  data: ReviewFlow[];
  meta: ReviewFlowListMeta;
}
