/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Alt Regioni API
 * API для работы с формами, шаблонами и файлами
 * OpenAPI spec version: 1.0.0
 */
import type { UploadFileBodyAccessLevel } from './uploadFileBodyAccessLevel';

export type UploadFileBody = {
  file: Blob;
  description?: string;
  accessLevel?: UploadFileBodyAccessLevel;
  folderId?: string;
};
