services:
  dev:
    image: 'mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm'
    container_name: dev
    restart: unless-stopped
    command: tail -f /dev/null
    volumes:
      - ../..:/workspaces:cached
    environment:
      - NODE_ENV=development
      - NITRO_PORT=3000
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev
volumes:
  postgres-data: